### ISSUE TITLE
Alternative of Open Ai Key

### ISSUE THREAD

**Issue by Kaivalya192** [ajzhai/NeRF2Physics#2]
Hello, impressed by your works !!
Can i use ollama or other llm in replacement of gpt ?
would it give same accuracy?
to work it offline also...
Thank you

**Comment by ajzhai** [comment]
Yes, you can! You just need to replace the GPT calls in `gpt_inference.py` with calls to your model:
https://github.com/ajzhai/NeRF2Physics/blob/6d81c093ed05434f31c0c735fdad1e51355bde86/gpt_inference.py#L64

I believe the accuracy should be similar using other recent LLMs.

**Comment by Kaivalya192** [comment]
> Yes, you can! You just need to replace the GPT calls in `gpt_inference.py` with calls to your model:
> 
> https://github.com/ajzhai/NeRF2Physics/blob/6d81c093ed05434f31c0c735fdad1e51355bde86/gpt_inference.py#L64
> 
> I believe the accuracy should be similar using other recent LLMs.

Thank you

**Comment by Kaivalya192** [comment]
Thank you
